name: Codelog

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v1

    - name: Init database
      run: |
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE USER codelog@localhost IDENTIFIED BY "codelog"'
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE test'
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE codelog'
        mysql -uroot -h127.0.0.1 -proot -e 'GRANT ALL PRIVILEGES ON test.* TO codelog@localhost IDENTIFIED BY "codelog" WITH GRANT OPTION'
        mysql -uroot -h127.0.0.1 -proot -e 'GRANT ALL PRIVILEGES ON codelog.* TO codelog@localhost IDENTIFIED BY "codelog" WITH GRANT OPTION'

    - name: Setup Python 3.8.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1

    - name: Install pipenv
      run: pip3 install pipenv

    - name: Install Dependencies
      run: pipenv install --system

    - name: Create database
      run: alembic upgrade head

    - name: Testing
      env:
        ENV: testing
      run: pytest

    - name: Build & Push image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        $(aws ecr get-login --no-include-email)
        docker build -t codelog .
        docker tag codelog ${{ secrets.ECR_URL }}
        docker push ${{ secrets.ECR_URL }}
